import { createContext, useContext } from 'react'

const defaultValue = {
  siteTitle: '',
  homeWelcomeTitle: '',
  homeWelcomeText: '',
  findOffersButtonText: '',
  directHelpButtonText: '',
  moreOffersKVBLinkText: '',
  moreOffersKVBLinkUrl: '',
  footerInfoPageLinkText: '',
  footerImprintLinkText: '',
  footerImprintLinkUrl: '',
  footerPrivacyLinkText: '',
  footerPrivacyLinkUrl: '',
  footerProjectOwnerLabel: '',
  footerTSBLogoAltText: '',
  footerTSBLogoLink: '',
  footerProjectExecutionerLabel: '',
  footerCityLABLogoAltText: '',
  footerCityLABLogoLink: '',
  footerCooperationLabel: '',
  footerSenWGPGLogoAltText: '',
  footerSenWGPGLogoLink: '',
  footerProjectSponsorLabel: '',
  footerSentatskanzleiLogoAltText: '',
  footerSentatskanzleiLogoLink: '',
  suicidePreventionLabel: '',
  suicidePreventionPhoneNumber: '',
  psychiatricServicesLabel: '',
  psychiatricServicesPhoneNumber: '',
  seelsorgeLabel: '',
  seelsorgePhoneNumber: '',
  backText: '',
  neighborhoodCharlottenburgWilmersdorfLabel: '',
  neighborhoodCharlottenburgWilmersdorfPhoneNumber: '',
  krisendienstCharlottenburgWilmersdorfPhoneNumber: '',
  neighborhoodFriedrichshainKreuzbergLabel: '',
  neighborhoodFriedrichshainKreuzbergPhoneNumber: '',
  krisendienstFriedrichshainKreuzbergPhoneNumber: '',
  neighborhoodLichtenbergLabel: '',
  neighborhoodLichtenbergPhoneNumber: '',
  krisendienstLichtenbergPhoneNumber: '',
  neighborhoodMarzahnHellersdorfLabel: '',
  neighborhoodMarzahnHellersdorfPhoneNumber: '',
  krisendienstMarzahnHellersdorfPhoneNumber: '',
  neighborhoodMitteLabel: '',
  neighborhoodMittePhoneNumber: '',
  krisendienstMittePhoneNumber: '',
  neighborhoodNeukoellnLabel: '',
  neighborhoodNeukoellnPhoneNumber: '',
  krisendienstNeukoellnPhoneNumber: '',
  neighborhoodPankowLabel: '',
  neighborhoodPankowPhoneNumber: '',
  krisendienstPankowPhoneNumber: '',
  neighborhoodReinickendorfLabel: '',
  neighborhoodReinickendorfPhoneNumber: '',
  krisendienstReinickendorfPhoneNumber: '',
  neighborhoodSpandauLabel: '',
  neighborhoodSpandauPhoneNumber: '',
  krisendienstSpandauPhoneNumber: '',
  neighborhoodSteglitzZehlendorfLabel: '',
  neighborhoodSteglitzZehlendorfPhoneNumber: '',
  krisendienstSteglitzZehlendorfPhoneNumber: '',
  neighborhoodTempelhofSchoenebergLabel: '',
  neighborhoodTempelhofSchoenebergPhoneNumber: '',
  krisendienstTempelhofSchoenebergPhoneNumber: '',
  neighborhoodTrepotowKoepenickLabel: '',
  neighborhoodTrepotowKoepenickPhoneNumber: '',
  krisendienstTrepotowKoepenickPhoneNumber: '',
  welcomeFiltersHeadline: '',
  welcomeFiltersText: '',
  filtersButtonTextFilteredSingular: '',
  filtersButtonTextFilteredPlural: '',
  filtersButtonTextFilteredNoResults: '',
  filtersButtonTextFilteredNoResultsHint: '',
  filtersButtonTextAllFilters: '',
  filtersGeoSearchLabel: '',
  noTargetPreferenceButtonText: '',
  orLabel: '',
  filtersSearchTargetLabel: '',
  filtersSearchTargetLabelOnCard: '',
  geolocationForbidden: '',
  opened: '',
  mapPageTitle: '',
  weekdayMonday: '',
  weekdayTuesday: '',
  weekdayWednesday: '',
  weekdayThursday: '',
  weekdayFriday: '',
  weekdaySaturday: '',
  weekdaySunday: '',
  filteredResultsAmountSingular: '',
  filteredResultsAmountPlural: '',
  resetFilters: '',
  noResults: '',
  seeMap: '',
  seeList: '',
  filterLabel: '',
  backToHome: '',
}

export type TextsMapType = typeof defaultValue

const textsContext = createContext<TextsMapType>(defaultValue)

export const useTexts = (): TextsMapType => {
  const texts = useContext(textsContext)
  return texts
}

export const TextsProvider = textsContext.Provider
