/*
# Get the data from berlin.de
*/
GET https://www.berlin.de/lb/psychiatrie/_assets/service/daten/datensatz_hilf-mir_berlin.csv

HTTP/1.1 200  - OK
date: Tue, 01 Aug 2023 09:46:48 GMT
content-type: application/octet-stream
content-length: 273325
connection: close
last-modified: Wed, 07 Jun 2023 15:07:19 +0200
cache-control: public, max-age=3600
content-disposition: attachment; filename="datensatz_hilf-mir_berlin.csv"
age: 1471
referrer-policy: strict-origin-when-cross-origin
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
strict-transport-security: max-age=31536000
content-security-policy: upgrade-insecure-requests
accept-ranges: bytes